version: "3"
services:
  pg_demo:
    image: postgres:alpine
    network_mode: bridge
    container_name: pg_demo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demodb
    restart: unless-stopped
  # APP*****************************************
  testapp1:
    image: testapp1:latest
    network_mode: bridge
    container_name: testapp1
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - pg_demo
    links:
      - pg_demo
volumes:
  postgres-data: